[package]
name = "fastly-edge-compute-poc"
version = "0.1.0"
edition = "2018"

[dependencies]
fastly = "^0.4.0"
http = "^0.2.1"
app = { path = "./crates/app" }

[workspace]
members = [
    ".",
    "crates/*"
]

[profile.release]
debug = true
