version = 11
name = "stef-edge-computer"
description = "Get to know the Fastly Compute@Edge environment with a basic starter that demonstrates routing, simple synthetic responses and overriding caching rules."
authors = ["stef.jones+ce-beta@condenast.com"]
language = "rust"
service_id = "54xcCkCPUIvqFr9W3Rg7D0"
